#!/bin/sh

set -x
set -e

git f
git co master && git r && git push private
git co v10.x && git r && git push private
git co v12.x && git r && git push private
git co v14.x && git r && git push private
