#!/bin/sh

set -x

# Set state to "clean" and stop, so that the stop process is slow, but the
# start process is fast.
microk8s.status && sudo microk8s.reset
microk8s.status && sudo microk8s.enable dns
sudo microk8s.stop
