#!/usr/bin/ruby -w

require 'ftools'

op = ARGV.empty? ? (raise "Usage: rename expr [files]\n") : ARGV.shift

argv = ARGV.empty? ? $stdin.readlines.map { |f| f.chomp } : ARGV

argv.each do |file|
  was = file
  file = eval("file.#{op}")
  File.move(was, file) unless was == file
end

