#!/usr/bin/ruby -w
# http://aheritier.net/clone-all-repositories-from-a-github-organization/
# FIXME it doesn't do private repos...

require "json"
require "open-uri"

json = open("https://api.github.com/orgs/strongloop/repos?per_page=1000").read

JSON.load(json).each do |repo|
  puts repo["ssh_url"]
  #%x{git clone #{repo["ssh_url"]} }
end
