#!/bin/sh

set -x

set -e

install=${1:-install}

pkg=$(pwd | sed -es'_.*/__')
rm -rf /tmp/stow-$pkg
# DESTDIR is autotools standard, INSTALL_PREFIX is OpenSSL :-(
make $install DESTDIR=/tmp/stow-$pkg INSTALL_PREFIX=/tmp/stow-$pkg
mkdir -p /usr/local/stow
rm -rf /usr/local/stow/$pkg
mv /tmp/stow-$pkg/usr/local /usr/local/stow/$pkg
cd /usr/local/stow && stow -R $pkg
