#!/bin/sh

set -e
set -x

# --file-tags=yes   Same as --extra=+f  ?
# --extra=+g   Unsupported?
# --fields=+iaS ?
ctags --if0=yes --recurse --extra=+fq --fields=+i \
  --c++-kinds=+p \
  --c-kinds=+p \
  --ruby-kinds=+cfFm \
  --langmap=c:+.m "$@"

