#!/bin/sh

where=${1:-$PWD}
where=$(readlink -f $where)
name=${2:-$(basename $where)}

mkdir -p $where

tmux new-window -c $where \; split-window -h -c $where \; split-window -v -c $where
tmux rename-window "$name"
